Morganey API
morganey-lang/Morganey pull request #200
Opened 2016-09-17 12:15 UTC by keddelzz

Prepare Morganey to be used via API (e.g. in the online REPL #182)

--
closes #199

2016-09-17 14:00 UTC, rexim commented on src/main/scala/me/rexim/morganey/interpreter/MorganeyRepl.scala
> +    // TODO(#197): discriminate bindings from the rest of the nodes here and inform the user if the binding was redefined
Just for the sake of issue linking: TODO(#197) was moved here.

2016-09-17 14:11 UTC, rexim requested changes
Manual testing detected a REPL bug:

```
λ> load prelude
λ> pair
Non-existing binding: pair
λ> pair 1 0
Non-existing binding: pair
λ> 
```

On the current master everything works as expected:

```
λ> load prelude
λ> pair
term: λx.y.z.z x y
λ> pair 1 0
numbers: [1]
λ> 
```

2016-09-17 14:23 UTC, keddelzz commented
Wow, what a stupid bug :laughing:

2016-09-17 14:40 UTC, rexim approved these changes

2016-09-17 14:43 UTC, rexim commented
@keddelzz Wow! That's an interesting situation indeed! It was also pretty hard to avoid. It feels like it's a nature of impertive impure approach we are using here. Very interesting...

2016-09-17 20:06 UTC, rexim commented
@ForNeVeR sorry we wanna merge it right now, I guess. Please feel free to leave your comments even after the merge. We will convert them into issues.

2016-09-17 20:07 UTC, rexim commented
@keddelzz thanks for the changes!

2016-09-17 20:07 UTC, merged

2016-09-18 06:41 UTC, ForNeVeR commented
Sorry guys I wasn't available and not still fully conscious at the moment. Will review everything later.

2016-09-18 09:01 UTC, rexim commented
@ForNeVeR no worries! Take your time!

2016-09-18 12:21 UTC, ForNeVeR reviewed
As for the changes they LGTM 👍

2016-09-18 12:42 UTC, rexim commented
@ForNeVeR cool! Thank you very much!