Functional tests
morganey-lang/Morganey pull request #203
Opened 2016-09-18 21:29 UTC by rexim

### Description

Addresses both #45 and #55 because it turned out they depend on each other. The PR resolves both of them. Since I'm really bad at sbt, my funtests infrastructure implementation probably could be better. Please provide your remarks when you get a chance. 

### Checklist

- [ ] Update docs
- [ ] Add/Update Unit Tests

---

Close #45, close #55

2016-09-18 21:40 UTC, rexim commented
Alright, looks funtests hang on Windows. I'm gonna fix that later.

2016-09-19 04:08 UTC, ForNeVeR commented
> looks funtests hang on Windows. I'm gonna fix that later.

Feel free to ask me if you need any help.

2016-09-19 04:58 UTC, rexim commented
> Feel free to ask me if you need any help.

@ForNeVeR sure! Thank you!

2016-09-27 11:44 UTC, rexim commented
Alright, it's been already more than a week. I'm gonna submit what I already done and split out the Windows funtests support.

2016-09-27 13:06 UTC, rexim commented
This is interesting. The result of REPL funtests heavily depends on the terminal implementation on Linux. I observed different results on gnome-terminal and Emacs. It's probably caused by jline. I'm gonna split out REPL funtests support too.

2016-09-27 13:30 UTC, rexim commented
@ForNeVeR @keddelzz PR is ready. Please take a look when you get a chance.

2016-09-27 13:33 UTC, ForNeVeR requested changes

2016-09-27 13:33 UTC, ForNeVeR commented on funtests/src/test/scala/me/rexim/morganey/funtests/FibFuntest.scala
> +    val actualOutput = "java -jar ./target/scala-2.11/morganey.jar ./docs/samples/fib.mgn".!!
I recommend to factor this out into a function or a constant, to remove the duplication of `"java -jar ./target/scala-2.11/morganey.jar"` everywhere.

2016-09-27 21:32 UTC, keddelzz approved these changes
Besides @ForNeVeR's suggested improvement; LGTM :+1:

2016-09-28 17:42 UTC, rexim commented on funtests/src/test/scala/me/rexim/morganey/funtests/FibFuntest.scala
> +    val actualOutput = "java -jar ./target/scala-2.11/morganey.jar ./docs/samples/fib.mgn".!!
Done

2016-09-29 03:18 UTC, ForNeVeR approved these changes

2016-09-29 08:33 UTC, rexim commented
@ForNeVeR @keddelzz thanks for the review guys!!

2016-09-29 08:33 UTC, merged