Setup assembly plugin
morganey-lang/Morganey pull request #211
Opened 2016-09-20 13:26 UTC by rexim

### Description

Extract fatjar config from #203 because of #208 

Close #45

2016-09-20 14:16 UTC, ForNeVeR commented on README.md
> +### Build an uber jar ###
I propose letter `ü` here because it's cool.

2016-09-20 14:16 UTC, ForNeVeR commented on README.md
> +
Also please specify a location of the überjar produced.

2016-09-20 14:17 UTC, ForNeVeR requested changes

2016-09-21 04:28 UTC, ForNeVeR commented on README.md
> +To build an übérjàr run the following command
Ugh that's too hot!

2016-09-21 04:28 UTC, ForNeVeR requested changes

2016-09-21 08:36 UTC, keddelzz approved these changes

2016-09-21 08:39 UTC, ForNeVeR approved these changes

2016-09-21 08:46 UTC, rexim commented
Thank you guys for the review!

2016-09-21 08:46 UTC, merged