Add more std-lib functions
morganey-lang/Morganey pull request #213
Opened 2016-09-21 09:19 UTC by keddelzz

2016-09-21 09:23 UTC, keddelzz commented
@rexim @ForNeVeR, i hope you're okay with me creating the label `component: std-lib`.

2016-09-21 16:08 UTC, rexim commented on std/list.mgn
> +map := \xs.f. Y (\mapRec.xs.f. (isnil xs) [] (cons (f (head xs)) (mapRec (tail xs) f))) xs f
I'd go with the same approach as Haskell: http://hackage.haskell.org/package/base-4.9.0.0/docs/Prelude.html#v:map

The map takes the function first. I think it's better because the following partial applications are more common:

``` morganey
succAll := map succ
succAll [1 .. 10]
```

2016-09-21 16:08 UTC, rexim commented on std/list.mgn
> +replicate := \x.n. Y (\replicateRec.n.x.i. (lt i n) (cons x (replicateRec n x (succ i))) []) n x 0
I'd take the number first for the same reason as for `map`. Binding the number of repeatitions is more common then binding `x`. Haskell agrees with me http://hackage.haskell.org/package/base-4.9.0.0/docs/Prelude.html#v:replicate

2016-09-21 16:08 UTC, rexim commented on std/list.mgn
> +foldl := \xs.zero.op. Y (\foldlRec.xs.acc.op. (isnil xs) acc (foldlRec (tail xs) (op acc (head xs)) op)) xs zero op
`\op.zero.xs.`. The same reason. It's more common to bind operation and the base element. http://hackage.haskell.org/package/base-4.9.0.0/docs/Prelude.html#v:foldl

2016-09-21 16:08 UTC, rexim commented on std/list.mgn
> +foldl := \xs.zero.op. Y (\foldlRec.xs.acc.op. (isnil xs) acc (foldlRec (tail xs) (op acc (head xs)) op)) xs zero op
Also `op` is already is the scope of inner function. No need to thread it through the entire iteration:

`\op.zero.xs. Y (\foldlRec.acc.xs. ???...`

2016-09-21 16:13 UTC, rexim commented on std/list.mgn
> +foldr := \xs.zero.op. foldl (reverse xs) zero (\a.b. op b a)
`\op.zero.xs.`

2016-09-21 16:13 UTC, rexim requested changes

2016-09-21 17:00 UTC, keddelzz commented
As for all of your comments, i do like Scala's parameter ordering better. In my opinion it's better to remember.

2016-09-21 17:17 UTC, rexim commented
@keddelzz what does make them easier to remember in your opinion?

2016-09-21 17:26 UTC, keddelzz commented
For me it's easier to remember, because it's the way I think about the operations.

- The function `map` maps the list `xs` with function `f`
```
map := \xs.f.  ...
```

--
- Creates a list containing `n` times `x`
```
replicate := \x.n.  ...
```

--
- The function `fold` folds together a list `xs` using a `zero` element if the list is empty. The function `op` is used to combine the accumulator and an element.
```
foldl := \xs.zero.op.  ...
```

--
I see the convenience, which is achieved by using Haskell's parameter ordering, but then I'll have to learn how to read the functions instead :)

2016-09-21 17:36 UTC, rexim commented
Well, sometimes we have to change our habbits ;) *cough* #143 *cough*

---

I mean I see where it comes from. In Scala all of these operations are methods of some objects. So technically you just can't  put `xs` not first. But there are no objects in Morganey...

@ForNeVeR @kuchenkruste @06needhamt what do you guys think? Which argument order is better for Morganey? Haskell or Scala?

2016-09-21 17:44 UTC, rexim commented
cc @Minoru

2016-09-21 17:56 UTC, Minoru commented
Disclaimer: I know Haskell better than I know Scala. I also like Haskell better than Scala.

I agree with @rexim's reasoning: since Morganey supports partial application, the arguments should be ordered such that the most common partial applications are convenient to write. (For everything else, there's `flip`.)

2016-09-21 18:33 UTC, keddelzz commented
Ok, let's wait on the answer of @ForNeVeR @kuchenkruste and @06needhamt.

2016-09-22 03:46 UTC, ForNeVeR commented
We have current argument order in Scala because of its object-oriented origin: `map` in Scala is the **method** of `Seq` trait that takes one argument. It's uncommon (or even syntactically impossible) to use method without the containing class in Scala, and that's an exact reason it's designed like that.

After all, `collection.map(function)` is perfectly okay and feels logical for an object-oriented world, but I doubt `function.map(collection)` would be the same. _(You could probably infer some additional understanding from connecting the `map` method with its typeclass origin, but let's stay aside from that for a moment.)_

On the other hand, Morganey, like Haskell, is not an object-oriented language. `map` is the first-class citizen in those languages. That's the reason it takes the function argument first: in a functional world it just makes more sense.

Summary: I agree with @rexim and vote for Haskell-style order of the arguments.

2016-09-25 10:05 UTC, keddelzz commented
Ok, I think we waited enough for @kuchenkruste and @06needhamt to answer. I'll change the parameter ordering to Haskell's for convenient partial application.

2016-09-25 10:18 UTC, rexim commented
@keddelzz thanks! I'll try to review the changes  before the stream. If not then tomorrow.

2016-09-26 06:02 UTC, rexim approved these changes
LGTM :+1: Thank you very much for the changes!

2016-09-26 06:02 UTC, merged