Use hidden-args in Morganey
morganey-lang/Morganey pull request #236
Opened 2016-10-01 18:00 UTC by keddelzz

closes #233

2016-10-01 18:45 UTC, rexim requested changes

2016-10-01 18:45 UTC, rexim commented on kernel/src/main/scala/me/rexim/morganey/ast/LambdaTerm.scala
> +  private[ast] def nestedFunctions(@hidden func: LambdaFunc     = this,
I'm sorry but this is just straight up ugly. Why not get rid of that redundant argument and pattern match the body of the LambdaFunc?

```scala
def nestedFunctions(@hidden acc: List[LambdaVar] = Nil): (List[LambdaVar], LambdaTerm) =
  body match {
    case f: LambdaFunc => f.nestedFunctions(parameter :: acc)
    case _             => ((parameter :: acc).reverse, body)
  }
```

2016-10-01 18:45 UTC, rexim commented on kernel/src/main/scala/me/rexim/morganey/ast/LambdaTerm.scala
> +  private[ast] def nestedApplications(@hidden app: LambdaApp        = this,
Same as for nestedFunctions

2016-10-01 19:45 UTC, rexim commented
@keddelzz, thank you! Looks much better! Sorry if I was too rude. I wanna perform some manual tests as well, but I'm already falling asleep. Gonna approve your PR tomorrow.

2016-10-01 20:15 UTC, keddelzz commented
> Sorry if I was too rude.

No need to apologize! You were absolutely right. It was ugly. :laughing:

2016-10-02 05:53 UTC, ForNeVeR approved these changes

2016-10-02 09:21 UTC, rexim approved these changes

2016-10-02 09:21 UTC, rexim commented
@keddelzz thanks for the changes!
@ForNeVeR thanks for the review!

2016-10-02 09:21 UTC, merged