Autocomplete unbind
morganey-lang/Morganey pull request #287
Opened 2016-10-30 19:30 UTC by keddelzz

closes #285

2016-10-30 19:39 UTC, rexim commented
@keddelzz that is so cool! Thanks! :) But I'm gonna review that later. Falling asleep already -_-

2016-10-30 20:32 UTC, keddelzz commented
>   But I'm gonna review that later.

No problem. :)

2016-10-31 20:05 UTC, rexim requested changes

2016-10-31 20:05 UTC, rexim commented on src/main/scala/me/rexim/morganey/Commands.scala
> +    hasTermArgument: Boolean)
Can we get rid of that? I mean it's no better than having a function with a boolean argument. Why can't it be something like

```scala
trait Command
case class StringCommand extends Command
case class TermCommand extends Command
```

2016-10-31 20:05 UTC, rexim commented on src/main/scala/me/rexim/morganey/ReplAutocompletion.scala
> +            if (c.hasTermArgument) c.name + " " else c.name
I don't understand this code. Could you please elaborate on what's going on here? Why do we care about term arguments whe we parse a simple command?

2016-11-01 04:31 UTC, ForNeVeR approved these changes
I have no objections except from what @rexim said.

2016-11-01 07:07 UTC, keddelzz commented on src/main/scala/me/rexim/morganey/ReplAutocompletion.scala
> +            if (c.hasTermArgument) c.name + " " else c.name
My goal with this code, was to autocomplete commands that have a term as an argument to ":command " (notice the space at the end). The space was, as far as I thought, necessary that the autocompletion for commands with arguments (`CommandWithArg`) can distinguish the command name and the arguments.

However, I was wrong. The space isn't needed.

I should have tested that earlier.

2016-11-01 11:31 UTC, rexim commented
@keddelzz thanks for the update! I'm gonna review it a bit later today.

2016-11-02 21:13 UTC, rexim requested changes

2016-11-02 21:13 UTC, rexim commented on src/main/scala/me/rexim/morganey/ReplAutocompletion.scala
> +          cmd.name == p && hasTermArgument(cmd)
Could you please inline `hasTermArgument` here like

```scala
commands.values find {
  case TermCommand(name, _) => name == p
  case _ => false
}
```

2016-11-04 14:27 UTC, rexim approved these changes

2016-11-04 14:27 UTC, rexim commented
@keddelzz thank you very much for the changes!
@ForNeVeR thanks for the review!

2016-11-04 14:27 UTC, merged