Refer to samples folder in README
morganey-lang/Morganey pull request #296
Opened 2016-11-07 15:22 UTC by rexim

Close #249

2016-11-07 15:24 UTC, ForNeVeR commented on README.md
> +    $ sbt "run docs/samples/fib.mgn"
I suggest to put such blocks into `console` environment such as:

    ```console
    $ sbt "run <path-to-sample>"
    ```

This way GitHub will color them more nicely.

2016-11-07 15:26 UTC, rexim commented on README.md
> +    $ sbt "run docs/samples/fib.mgn"
Wow! Didn't know that such thing exists! Let me try it...

2016-11-07 15:28 UTC, rexim commented on README.md
> +    $ sbt "run docs/samples/fib.mgn"
@ForNeVeR looks cool! Thanks!

2016-11-07 15:38 UTC, ForNeVeR approved these changes

2016-11-07 15:39 UTC, ForNeVeR requested changes

2016-11-07 15:39 UTC, ForNeVeR commented on README.md
> +from the root of the source code directory. For example, to run the 15 first fibonacci numbers sample run:
I suggest to replace the first "run" in this line with "print".

2016-11-07 18:19 UTC, keddelzz approved these changes
:+1: LGTM

2016-11-08 18:31 UTC, rexim commented on README.md
> +from the root of the source code directory. For example, to run the 15 first fibonacci numbers sample run:
"To print 15 first fibonacci sample"? What "printing a sample" is supposed to mean in this context? I'd replace it with `execute`. Let me do that.

2016-11-09 03:17 UTC, ForNeVeR approved these changes

2016-11-09 03:19 UTC, ForNeVeR commented
AppVeyor failed to start the job again for some reason, but that shouldn't block the merge.

Also, probably something is strange with our AppVeyor setup; such periodic failures are unusual. I'll take a look at our setup later.

2016-11-09 04:14 UTC, rexim commented
@ForNeVeR hope you don't mind that I created an issue for that and assigned to you.

2016-11-09 04:24 UTC, ForNeVeR commented
@rexim thanks!

2016-11-10 03:11 UTC, rexim commented
@ForNeVeR @keddelzz thanks for the review guys!

2016-11-10 03:11 UTC, merged