Added turing machine example
morganey-lang/Morganey pull request #298
Opened 2016-11-08 20:00 UTC by kuchenkruste

Finally I had the time to write a turing machine in Morganey!

Theoretically it can execute any turing machine program (and thus shows that Morganey is turing complete!). 

Unfortunately the morganey program itself has a runtime complexity which is nearly exponential. This behavior is the result of the evaluation strategy "call-by-name" Morganey uses. It could be fixed by using the "call-by-need" strategy. 

But where does this come from? Every time a turing machine is executed in a particular state (lets call it state "n"), it also executes the machine in the previous state ("n - 1"). Because parameters are evaluated each time they are used, the machine in state "n" executes the machine in state "n - 1" not only once, but a few times. The machine in state "n - 1" does the same and so on. As one can imagine, the algorithm builds up a tree of turing machines.

The evaluation strategy "call-by-need" would fix that problem, because once the machine in state "n - 1" is calculated it would never have to be calculated again. So the machine in state "n" would calculate the machine in state "n - 1", where the machine in state "n - 1" would calculate the machine in state "n - 2" and so on.  If I've not messed up, this should reduce the runtime complexity to a linear behavior.

I've added a brief explanation of the usage to the file.

2016-11-09 04:17 UTC, rexim commented
@kuchenkruste this is so cool!! :)

I'll try to take a look later today. Thanks!

2016-11-09 10:33 UTC, Newlifer commented
Awesome!

2016-11-10 03:28 UTC, rexim commented
> This behavior is the result of the evaluation strategy "call-by-name" Morganey uses.

Your assumption is wrong. Morganey doesn't use call-by-name evaluation strategy. It uses normal order. Please see #84 for more info on that.

2016-11-10 03:37 UTC, rexim requested changes
How long is the example at the bottom is supposed to work? I just uncommented it, ran with `sbt "run docs/samples/turing-machine.mgn"` and waited for ~10 minutes. The program was hanging.

Linux, Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz

Was it ok on your system?

2016-11-10 03:37 UTC, rexim commented on docs/samples/turing-machine.mgn
> + */
I'd suggest to organize the comments in this section like:

```c
/** Example usage: */
/*
def tape := []
def program := [
  [1, 0, 1, 1, 2],
  [1, 2, 'x', 1, 0],
  [2, 0, 2, 1, 3],
  [3, 0, 1, 0, 1]
]
def head := 0
def start := 1
def machine := newMachine tape head start program
def main := runMachine machine 
*/
```

It makes it easier to uncomment even in the most minimalistic text editor in the world.

2016-11-10 06:59 UTC, BjoernLoetters commented on docs/samples/turing-machine.mgn
> + */
I'll do that by tomorrow.

2016-11-17 21:27 UTC, kuchenkruste commented
I've changed the example usage comment. 

> How long is the example at the bottom is supposed to work?

To be honest: I don't know. So far only machines with `<= 2` states terminated on my PC. But you can execute the example step by step: 
1. Replace `def main := runMachine machine` with `def main := executeStep machine` 
2. Overwrite the machine `machine` with the computed machine (this is the machine which is in state `n + 1`)
3. Repeat step 1. and 2. as long as the state of the machine is not `0`

>> This behavior is the result of the evaluation strategy "call-by-name" Morganey uses.

> Your assumption is wrong. Morganey doesn't use call-by-name evaluation strategy. It uses normal order. 

Probably I've messed something up - but the point is, that as long as morganey evaluates parameters (i.e. the expressions which are bound to them) each time they are used, the runtime won't get any better.

2016-11-18 08:34 UTC, rexim commented
> To be honest: I don't know. So far only machines with `<= 2` states terminated on my PC

Cool! Thanks for the information.

> Probably I've messed something up - but the point is, that as long as morganey evaluates parameters (i.e. the expressions which are bound to them) each time they are used, the runtime won't get any better.

Got it thanks!

2016-11-18 08:34 UTC, rexim approved these changes

2016-11-18 08:36 UTC, rexim commented
@kuchenkruste thank you very much for such an awesome sample! :)

A bit later I'll create an issue to address the performance concern. I think it should be discussed separately.

2016-11-18 08:36 UTC, merged