Refactor ReplAutocompletion
morganey-lang/Morganey pull request #302
Opened 2016-11-20 15:49 UTC by rexim

### Checklist

- [X] ~Update docs~
- [X] Add/Update Unit Tests

---

Close #284

2016-11-20 16:05 UTC, ForNeVeR requested changes

2016-11-20 16:05 UTC, ForNeVeR commented on src/main/scala/me/rexim/morganey/module/ModuleFinder.scala
> +    * Imaging having a two folders in the morganey path `modsA` and `modsB`:
I'm not a language expert, but shouldn't `Imaging` be `Imagine` here?

2016-11-20 17:40 UTC, keddelzz commented on src/main/scala/me/rexim/morganey/module/ModuleFinder.scala
> +    * Imaging having a two folders in the morganey path `modsA` and `modsB`:
I think so, too :)

2016-11-20 17:46 UTC, rexim commented on src/main/scala/me/rexim/morganey/module/ModuleFinder.scala
> +    * Imaging having a two folders in the morganey path `modsA` and `modsB`:
Fxd

2016-11-20 18:51 UTC, keddelzz approved these changes

2016-11-21 04:22 UTC, ForNeVeR approved these changes

2016-11-21 04:27 UTC, rexim commented
@keddelzz @ForNeVeR thanks for the review!

2016-11-21 04:27 UTC, merged