[WIP] Find all modules in Morganey indices
morganey-lang/Morganey pull request #308
Opened 2016-11-27 17:42 UTC by rexim

### Remaining Work

- Extend Morganey index so it contains module container id
- Develop mechanism for filtering out particular module containers by their id
- Implement specs for `ModuleFinder.findAllModulesInClasspath`

Split #305

2016-11-27 20:18 UTC, rexim commented on src/main/scala/me/rexim/morganey/module/ModuleFinder.scala
> +  def findAllModulesInClasspath(): Set[String] = {
I think it's better to rename it to something like `findAllModulesInIndex` to emphasize that it's not the only way of discovering modules. It is also possible to access a module if you know its full path, even if such module is not registered in the Morganey index.

2016-11-28 03:52 UTC, ForNeVeR requested changes
I think that's a good moment to add some tests for this function. If you prefer to not mess with classpath, you could use mocked ClassLoader or something like that. Probably API of this function needs to be changed (I think that's a good idea to pass `ClassLoader` as a parameter to test it easier).

2016-11-28 06:24 UTC, rexim commented
@ForNeVeR wow! I didn't even think about mocking ClassLoader for testing! I feel so dumb now! :D Thank you very much!

If we are able to mock ClassLoader for testing we don't need all of that bullshit with filtering module containers that I suggested in the description of this PR. I'm gonna address that a bit later. Thanks!

2016-11-28 16:15 UTC, keddelzz approved these changes

2016-12-02 18:13 UTC, rexim commented
@ForNeVeR @keddelzz @kuchenkruste quick question. Which mocking framework would you use for Morganey and why?

2016-12-03 04:50 UTC, ForNeVeR commented
@rexim I actually have no experience with mocks in Scala, so I'd go with ScalaMock, because it have an obvious name :)

2016-12-04 09:26 UTC, rexim commented
My personal answer on the above question is mockito, because I already know it, it just works and ScalaTest supports it in a form of [MockitoSugar](http://doc.scalatest.org/1.8/org/scalatest/mock/MockitoSugar.html).

2016-12-04 09:27 UTC, rexim commented
If no additional answers are provided within two hours starting from now I'm applying mockito and we are going with it. Just wanna close this one before the stream. :)

2016-12-04 12:02 UTC, rexim commented
Time's up! Thanks everyone! The PR is ready for the review.

2016-12-04 12:07 UTC, ForNeVeR approved these changes

2016-12-04 12:31 UTC, rexim commented
@ForNeVeR @keddelzz thank you guys for the review!

I guess appveyor/pr is gonna hang again, so I'm mergin this one.

2016-12-04 12:31 UTC, merged